# Generated by Django 3.2.5 on 2022-06-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220609_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Courier Name')),
                ('can_cancel_shipment', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'courier',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipmentlabel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipment_label_product', to='api.product'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_courier', to='api.courier'),
        ),
    ]
