# Generated by Django 3.2.5 on 2022-06-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220611_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('processing', 'shipment is processing.'), ('in_transit', 'Shipment in transit.'), ('shipped', 'Shipment completed.')], default='processing', max_length=255),
        ),
    ]
