# Generated by Django 3.2.5 on 2022-06-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='can_cancel_shipment',
            field=models.BooleanField(default=True),
        ),
    ]
