# Generated by Django 3.2.5 on 2022-06-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220613_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('processing', 'shipment is processing.'), ('in transit', 'Shipment in transit.'), ('shipped', 'Shipment completed.')], default='processing', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
